<project>
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.5</version>
		<relativePath/>
	</parent>

	<groupId>com.example</groupId>
	<artifactId>pvt-15-backend</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<java.version>17</java.version>
	</properties>

	<modules>
		<module>auth-service</module>
		<module>storage-service</module>
		<module>picture-service</module>
		<module>core-service</module>
	</modules>
</project>