spring.application.name=accessing-data-mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.url=@DB_URL@
spring.datasource.username=@DB_USERNAME@
spring.datasource.password=@DB_PASSWORD@
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

jwt.secret=@JWT_SECRET@
jwt.expiration-hours=24
google.client-id=@GOOGLE_CLIENT_ID@

vision.api.key=@VISION_API_KEY@
plantnet.api.key=@PLANTNET_API_KEY@
plantnet.project=all

gcs.bucket-name=@GCS_BUCKET_NAME@
gcs.project-id=@GCP_PROJECT_ID@
gcs.credentials.base64=@GCS_CREDENTIALS_B64@

challenge.admin.key=@ADMIN_KEY@