spring.application.name=picture-service
server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.url=@DB_URL@
spring.datasource.username=@DB_USERNAME@
spring.datasource.password=@DB_PASSWORD@
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

jwt.secret=@JWT_SECRET@

vision.api.key=@VISION_API_KEY@
plantnet.api.key=@PLANTNET_API_KEY@
plantnet.project=all

challenge.admin.key=@ADMIN_KEY@

services.storage.base-url=http://localhost:8082