spring.application.name=storage-service

jwt.secret=@JWT_SECRET@

gcs.bucket-name=@GCS_BUCKET_NAME@
gcs.project-id=@GCP_PROJECT_ID@
gcs.credentials-base64=@GCS_CREDENTIALS_B64@

services.auth.base-url=http://localhost:8080/auth-service